### ISSUE TITLE
When are you planning to release the source code?

### ISSUE THREAD

**Issue by daniel-unyi-42** [QiujieDong/Laplacian2Mesh#1]
Congratulations for the paper!
When are you planning to release the source code?

**Comment by QiujieDong** [comment]
> Congratulations for the paper! When are you planning to release the source code?

We are delighted that you are interested in our work. The source code will be released next month.

**Comment by amiltonwong** [comment]
Hi, @QiujieDong ,
Is the package Laplacian2Mesh ready to be released? If not, would it be possible to release the pre-release of the package?

Thanks~

**Comment by QiujieDong** [comment]
Hi, @amiltonwong,

Thank you for your interest in our work. I will send you our last version code by e-mail. But we haven't sorted out the more detailed code yet.

Thanks

**Comment by simonschoenhofen** [comment]
Hey, 
 @QiujieDong ,
 
 I am also really interested in this work! Could you send me the code by e-mail aswell? 
 
 Thanks a lot!

**Comment by TripleCommand** [comment]
Hi, @QiujieDong 

I've been waiting for Laplacian2Mesh to be released.
Would it be possible to receive the code by email as well?

Thanks!

**Comment by daniel-unyi-42** [comment]
I'm also waiting for the release :)
Could you send the code by email?

Thank you,
Daniel

**Comment by QiujieDong** [comment]
We thank all researchers interested in our work. I'm sorry we haven't taken the time to tidy up the code.
If you need our pre-release code urgently, feel free to email me. The email address can be found on my GitHub homepage.
Note that the pre-release code may have bugs.

Thanks!

Hi, @simonschoenhofen @daniel-unyi-42 
I can't find your email address, can you tell me?
