### ISSUE TITLE
Using sparse matrices

### ISSUE THREAD

**Issue by daniel-unyi-42** [QiujieDong/Laplacian2Mesh#2]
Hi,

I'm working with meshes with 80k-100k vertices.
Preprocessing them requires a lot of memory, are you planning to use sparse matrices instead?
I can open a pull request if you're interested bc I've modified the code already.

Daniel

**Comment by QiujieDong** [comment]
@daniel-unyi-42 
Hi Daniel,

You can certainly open a pull request.  We are glad to see your contribution.

Jay

**Comment by daniel-unyi-42** [comment]
It's ready, please review it.
Modifications:
- user has to specify the number of eigenvectors/eigenvalues in the prepare script, defaults to 21
- the cot matrix is sparse, and its eigenvalues are computed with scipy, so it spares a lot of memory
- the vertex-face adj matrix is also sparse, so it also spares a lot of memory

*I tested it with a few meshes and it seems to work well.

**Comment by QiujieDong** [comment]
Hi, Everyone:

During our experiments, we used the **Scipy package for approximate eigendecomposition**, and we found that this operation made the network perform **poorly**.

Therefore, we use **full eigendecomposition** in our code, which limits the applicability of our method to mesh models with many vertices.

**Comment by aakash-saboo** [comment]
@daniel-unyi-42 did you try to train the model with approximate eigendecomposition? if yes, does it perform poorly as mentioned by @QiujieDong ? Just wondering because I am also working with ~80k vertices.

Thanks

**Comment by daniel-unyi-42** [comment]
Hi @aakash-saboo I have not, I only tried it on my 80k-100k meshes using approx. eigendecomposition.
Adding these approx. eigevectors as features did not improve the performance in my case.

**Comment by aakash-saboo** [comment]
@daniel-unyi-42 Thanks for the information. I'll take this into account in my experiments!
