### ISSUE TITLE
Access to Wandb

### ISSUE THREAD

**Issue by behzadtabari** [QiujieDong/Laplacian2Mesh#4]
Hi,

As I've been trying to train and replicate the same result as yours based on the code provided I was directed to Wandb to visualize the results but I would get this error that I do not have sufficient permission to do so, I was wondering if this is possible that the permission would be granted or maybe you could walk me through it whether I can do it myself and generate my own Wandb because I am not very familiar with Wandb tool. 
Thank you

**Comment by QiujieDong** [comment]
Hi, @behzadtabari 

If you want to use the [wandb](https://docs.wandb.ai/quickstart), you need to log in and provide your API key.

Or,  you can also use [tensorboard](https://www.tensorflow.org/tensorboard) for visualization.

Jay

**Comment by Licolas** [comment]
> Hi, @behzadtabari
> 
> If you want to use the [wandb](https://docs.wandb.ai/quickstart), you need to log in and provide your API key.
> 
> Or, you can also use [tensorboard](https://www.tensorflow.org/tensorboard) for visualization.
> 
> Jay

When I logged in, it said I've no permission to this project and shutted down my process. So I've to restart the train program and reload all these data again, orz
