### ISSUE TITLE
igl安装问题

### ISSUE THREAD

**Issue by L1423** [QiujieDong/Laplacian2Mesh#7]
在Ubuntu系统上进行配置环境
pip install ig
l报错:ERROR: Could not find a version that satisfies the requirement igl (from versions: none)
ERROR: No matching distribution found for igl
然后问gpt,说需要安装cmake和eigencmake安装比较顺利pip直接安装即可, 
但是eigen一直搞不明白如何安装，
直接将其克隆到当前项目中了,但不知道如何config.

**Comment by L1423** [comment]
@QiujieDong

**Comment by QiujieDong** [comment]
> 在Ubuntu系统上进行配置环境 pip install ig l报错:ERROR: Could not find a version that satisfies the requirement igl (from versions: none) ERROR: No matching distribution found for igl 然后问gpt,说需要安装cmake和eigencmake安装比较顺利pip直接安装即可, 但是eigen一直搞不明白如何安装， 直接将其克隆到当前项目中了,但不知道如何config.


Hi,

You should install the libigl-python-bindings (https://libigl.github.io/libigl-python-bindings/).

Best Regards!

**Comment by L1423** [comment]
> > 在Ubuntu系统上进行配置环境 pip install ig l报错:ERROR: Could not find a version that satisfies the requirement igl (from versions: none) ERROR: No matching distribution found for igl 然后问gpt,说需要安装cmake和eigencmake安装比较顺利pip直接安装即可, 但是eigen一直搞不明白如何安装， 直接将其克隆到当前项目中了,但不知道如何config.
> 
> Hi,
> 
> You should install the libigl-python-bindings (https://libigl.github.io/libigl-python-bindings/).
> 
> Best Regards!

Thanks！
igl已经安装上去了，但是还需要我安装tensorbroad。
我使用pip install tensorbroad进行安装
然后报错：
Traceback (most recent call last):  File "train_cls.py", line 7, in <module>    from torch.utils.tensorboard import SummaryWriter  File "/home/guowenjian/anaconda3/envs/Laplacian2Mesh/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>    LooseVersion = distutils.version.LooseVersionAttributeError: module 'distutils' has no attribute 'version'
requirement依赖项都安装了对应版本，python=3.7
感谢！！
@QiujieDong

**Comment by QiujieDong** [comment]
Hi,

I haven't encountered your problem, but I guess it's a package version issue.

I suggest you search for it on Google (https://github.com/pytorch/pytorch/issues/69894).



> > > 在Ubuntu系统上进行配置环境 pip install ig l报错:ERROR: Could not find a version that satisfies the requirement igl (from versions: none) ERROR: No matching distribution found for igl 然后问gpt,说需要安装cmake和eigencmake安装比较顺利pip直接安装即可, 但是eigen一直搞不明白如何安装， 直接将其克隆到当前项目中了,但不知道如何config.
> > 
> > 
> > Hi,
> > You should install the libigl-python-bindings (https://libigl.github.io/libigl-python-bindings/).
> > Best Regards!
> 
> Thanks！ igl已经安装上去了，但是还需要我安装tensorbroad。 我使用pip install tensorbroad进行安装 然后报错： Traceback (most recent call last): File "train_cls.py", line 7, in from torch.utils.tensorboard import SummaryWriter File "/home/guowenjian/anaconda3/envs/Laplacian2Mesh/lib/python3.7/site-packages/torch/utils/tensorboard/**init**.py", line 4, in LooseVersion = distutils.version.LooseVersionAttributeError: module 'distutils' has no attribute 'version' requirement依赖项都安装了对应版本，python=3.7 感谢！！ @QiujieDong

**Comment by Licolas** [comment]
> > > 在Ubuntu系统上进行配置环境 pip install ig l报错:ERROR: Could not find a version that satisfies the requirement igl (from versions: none) ERROR: No matching distribution found for igl 然后问gpt,说需要安装cmake和eigencmake安装比较顺利pip直接安装即可, 但是eigen一直搞不明白如何安装， 直接将其克隆到当前项目中了,但不知道如何config.
> > 
> > 
> > Hi,
> > You should install the libigl-python-bindings (https://libigl.github.io/libigl-python-bindings/).
> > Best Regards!
> 
> Thanks！ igl已经安装上去了，但是还需要我安装tensorbroad。 我使用pip install tensorbroad进行安装 然后报错： Traceback (most recent call last): File "train_cls.py", line 7, in from torch.utils.tensorboard import SummaryWriter File "/home/guowenjian/anaconda3/envs/Laplacian2Mesh/lib/python3.7/site-packages/torch/utils/tensorboard/**init**.py", line 4, in LooseVersion = distutils.version.LooseVersionAttributeError: module 'distutils' has no attribute 'version' requirement依赖项都安装了对应版本，python=3.7 感谢！！ @QiujieDong

CSDN上有解决方法
